### ISSUE TITLE
Discourse seems to be down

### ISSUE THREAD

**Issue by brainwane** [numfocus/collab-infrastructure#38]
https://discourse.numfocus.org/ gives me an error 500; I'm not sure how long it's been down.

(Incidentally, thanks for https://wiki.numfocus.org/Collaboration_Infrastructure/Discussion_Forum which was very clear on how I should report an issue about this!)

**Comment by aterrel** [comment]
Thanks for the report. We'll look into the outage and report back.

**Comment by aterrel** [comment]
I believe service has been restored. Please let me know if you experience any other trouble.
